# port
server.port = 80

# Oracle Connection
spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}
spring.datasource.url=${RDS_URL}

# Redis
spring.session.store-type=redis
spring.data.redis.host = ${REDIS_HOST}
spring.data.redis.port = ${REDIS_PORT}

batchDnsName = ${BATCH_DNS_NAME}

# coolsms
coolsms.api.key= ${COOLSMS_API_KEY}
coolsms.api.secret= ${COOLSMS_API_SECRET}

# JPA Config
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
logging.level.org.hibernate=debug
logging.level.org.hibernate.type=trace




# H2 Database
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:~/dev_btch
#spring.datasource.username=sa
#spring.datasource.password=1234
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect